# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread
from PyQt5.QtCore import pyqtSignal
import sys
import time
import math
from datetime import datetime
import os
from PyQt5.QtWidgets import QApplication, QMainWindow
import cx_Oracle
import os,cv2

try:
    _fromUtf8 = QtWidgets.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s


try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        self.conn = cx_Oracle.connect('TJOCR/TJOCR@127.0.0.1/orcl')
        # conn= cx_Oracle.connect('airport/jcfj@10.92.172.110/orcl')
        self.cursor = self.conn.cursor()
        self.sqlstring = "select * from（select * from PSG_AJ_OCR order by NO desc）where rownum=1 AND"
        self.sqlstring1 = "select * from（select * from PSG_AJ_ZC order by ID desc）where rownum=1 AND"
        self.sqlstring2 = "select * from PSG_AJ_IDCARD_FACE where"

        MainWindow.resize(869, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 851, 571))
        self.tabWidget.setObjectName("tabWidget")
        stylesheet = """ 
         QTabBar::tab:selected {background: gray;}
         QTabWidget>QWidget>QWidget{background: gray;}
        """
        self.setStyleSheet(stylesheet)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 631, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 0, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 9, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 9, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 7, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 6, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 4, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 7, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 8, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 2, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 4, 4, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 6, 4, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 3, 4, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 8, 4, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 7, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 5, 4, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout.addWidget(self.lineEdit_40, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 1, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 3, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 0, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 9, 0, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout.addWidget(self.lineEdit_41, 9, 2, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(680, 50, 101, 101))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_2.setGeometry(QtCore.QRect(680, 200, 101, 101))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(680, 10, 91, 41))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(680, 160, 81, 31))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        stylesheet = """ 
         QTabBar::tab:selected {background: gray;}
         QTabWidget>QWidget>QWidget{background: gray;}
        """
        self.tab_2.setStyleSheet(stylesheet)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 601, 511))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_2.addWidget(self.lineEdit_35, 7, 3, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_2.addWidget(self.lineEdit_34, 6, 3, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_2.addWidget(self.lineEdit_29, 1, 3, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_2.addWidget(self.lineEdit_30, 2, 3, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_2.addWidget(self.lineEdit_31, 3, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_2.addWidget(self.lineEdit_32, 4, 3, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_2.addWidget(self.lineEdit_33, 5, 3, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_2.addWidget(self.checkBox_17, 7, 2, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_2.addWidget(self.lineEdit_36, 8, 3, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_2.addWidget(self.lineEdit_27, 8, 1, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_2.addWidget(self.checkBox_18, 8, 2, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 0, 2, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_2.addWidget(self.lineEdit_28, 0, 3, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 1, 2, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_2.addWidget(self.lineEdit_25, 6, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_2.addWidget(self.lineEdit_26, 7, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_2.addWidget(self.lineEdit_20, 1, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_2.addWidget(self.lineEdit_19, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 5, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 6, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_2.addWidget(self.checkBox_8, 7, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 2, 2, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_2.addWidget(self.checkBox_13, 3, 2, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_2.addWidget(self.checkBox_15, 5, 2, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_2.addWidget(self.checkBox_14, 4, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_2.addWidget(self.checkBox_9, 8, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_2.addWidget(self.lineEdit_22, 3, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_2.addWidget(self.lineEdit_24, 5, 1, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_2.addWidget(self.checkBox_16, 6, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_2.addWidget(self.lineEdit_23, 4, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_2.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_2.addWidget(self.checkBox_21, 9, 0, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_2.addWidget(self.lineEdit_42, 9, 1, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_2.addWidget(self.checkBox_22, 9, 2, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_2.addWidget(self.lineEdit_43, 9, 3, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(630, 40, 181, 131))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_3.addWidget(self.checkBox_19, 0, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_3.addWidget(self.dateEdit_2, 1, 1, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_3.addWidget(self.checkBox_20, 2, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 2, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(630, 360, 181, 81))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(630, 180, 54, 12))
        self.label_21.setObjectName("label_21")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(630, 210, 181, 101))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_5.addWidget(self.lineEdit_37, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_5.addWidget(self.lineEdit_38, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 0, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_5.addWidget(self.lineEdit_39, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(630, 10, 54, 12))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(630, 330, 54, 12))
        self.label_26.setObjectName("label_26")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        stylesheet = """ 
                 QTabBar::tab:selected {background: gray;}
                 QTabWidget>QWidget>QWidget{background: gray;}
                """
        self.tab_3.setStyleSheet(stylesheet)
        self.tab_3.setObjectName("tab_3")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_3.setGeometry(QtCore.QRect(20, 30, 551, 491))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(590, 30, 231, 241))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 4, 1, 1, 1)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.gridLayoutWidget_6)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.gridLayout_6.addWidget(self.dateEdit_3, 0, 1, 1, 1)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.gridLayoutWidget_6)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.gridLayout_6.addWidget(self.dateEdit_4, 2, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_6.addWidget(self.spinBox_2, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "航班号"))
        self.label_10.setText(_translate("MainWindow", "座位号"))
        self.label_16.setText(_translate("MainWindow", "起飞时间"))
        self.label_14.setText(_translate("MainWindow", "登机口"))
        self.label_15.setText(_translate("MainWindow", "起飞日期"))
        self.label_12.setText(_translate("MainWindow", "陪人数"))
        self.label_11.setText(_translate("MainWindow", "行李数"))
        self.label_7.setText(_translate("MainWindow", "证件类型"))
        self.label_20.setText(_translate("MainWindow", "旅客编号"))
        self.label_3.setText(_translate("MainWindow", "民族"))
        self.label_4.setText(_translate("MainWindow", "出生日期"))
        self.label_6.setText(_translate("MainWindow", "有效期"))
        self.label_13.setText(_translate("MainWindow", "登机号"))
        self.label.setText(_translate("MainWindow", "姓名"))
        self.label_2.setText(_translate("MainWindow", "性别"))
        self.label_5.setText(_translate("MainWindow", "住址"))
        self.label_30.setText(_translate("MainWindow", "机器号"))
        self.label_8.setText(_translate("MainWindow", "订票证件号"))
        self.label_19.setText(_translate("MainWindow", "屏幕手持证件号"))
        self.label_31.setText(_translate("MainWindow", "入客户端时间"))
        self.label_17.setText(_translate("MainWindow", "证件原图缩略图"))
        self.label_18.setText(_translate("MainWindow", "证件人像切图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "显示"))
        self.checkBox_17.setText(_translate("MainWindow", "登机口"))
        self.checkBox_18.setText(_translate("MainWindow", "起飞日期"))
        self.checkBox_10.setText(_translate("MainWindow", "屏幕手持证件号"))
        self.checkBox_11.setText(_translate("MainWindow", "订票证件号"))
        self.checkBox_2.setText(_translate("MainWindow", "机器号"))
        self.checkBox_4.setText(_translate("MainWindow", "性别"))
        self.checkBox_6.setText(_translate("MainWindow", "出生日期"))
        self.checkBox_7.setText(_translate("MainWindow", "住址"))
        self.checkBox_5.setText(_translate("MainWindow", "民族"))
        self.checkBox.setText(_translate("MainWindow", "旅客编号"))
        self.checkBox_8.setText(_translate("MainWindow", "有效期"))
        self.checkBox_3.setText(_translate("MainWindow", "姓名"))
        self.checkBox_12.setText(_translate("MainWindow", "航班号"))
        self.checkBox_13.setText(_translate("MainWindow", "座位号"))
        self.checkBox_15.setText(_translate("MainWindow", "陪人数"))
        self.checkBox_14.setText(_translate("MainWindow", "行李数"))
        self.checkBox_9.setText(_translate("MainWindow", "证件类型"))
        self.checkBox_16.setText(_translate("MainWindow", "登机号"))
        self.checkBox_21.setText(_translate("MainWindow", "入客户端时间"))
        self.checkBox_22.setText(_translate("MainWindow", "起飞时间"))
        self.checkBox_19.setText(_translate("MainWindow", "时间区间"))
        self.checkBox_20.setText(_translate("MainWindow", "机器号"))
        self.pushButton_3.setText(_translate("MainWindow", "导出"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.pushButton_2.setText(_translate("MainWindow", "清空"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.label_21.setText(_translate("MainWindow", "统计信息"))
        self.label_23.setText(_translate("MainWindow", "女性"))
        self.label_22.setText(_translate("MainWindow", "男性"))
        self.label_24.setText(_translate("MainWindow", "总人数"))
        self.label_25.setText(_translate("MainWindow", "选择条件"))
        self.label_26.setText(_translate("MainWindow", "功能区"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "查询"))
        self.pushButton_5.setText(_translate("MainWindow", "开始"))
        self.label_27.setText(_translate("MainWindow", "模式选择"))
        self.label_28.setText(_translate("MainWindow", "从"))
        self.label_29.setText(_translate("MainWindow", "到"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "分析"))


    def buttonExit(self):
        self.close()

    def buttonclear(self):
        self.lineEdit_19.clear()
        self.lineEdit_20.clear()
        self.lineEdit_21.clear()
        self.lineEdit_22.clear()
        self.lineEdit_23.clear()
        self.lineEdit_24.clear()
        self.lineEdit_25.clear()
        self.lineEdit_26.clear()
        self.lineEdit_27.clear()
        self.lineEdit_28.clear()
        self.lineEdit_29.clear()
        self.lineEdit_30.clear()
        self.lineEdit_31.clear()
        self.lineEdit_32.clear()
        self.lineEdit_33.clear()
        self.lineEdit_34.clear()
        self.lineEdit_35.clear()
        self.lineEdit_36.clear()
        self.lineEdit_42.clear()
        self.lineEdit_43.clear()

    def buttonsearch(self):
        temp_sqlstring = self.sqlstring
        temp_sqlstring1 = self.sqlstring1
        temp_sqlstring2 = self.sqlstring2
        is_first = True
        if self.checkBox_3.isChecked():
            if is_first:
                is_first = False
                temp_sqlstring += " NAME='%s'" % self.lineEdit_21.text()
            else:
                temp_sqlstring += " and NAME='%s'" % self.lineEdit_21.text()

        self.cursor.execute(temp_sqlstring)
        data = self.cursor.fetchall()
        for rec in data:
            self.lineEdit_21.setText(rec[5])
            self.lineEdit_22.setText(rec[6])
            self.lineEdit_23.setText(rec[7])
            self.lineEdit_24.setText(rec[8])
            self.lineEdit_25.setText(rec[9])
            self.lineEdit_26.setText(rec[11])
            self.lineEdit_27.setText(str(rec[17]))
            self.lineEdit_42.setText(str(rec[15]))
            temp_sqlstring1 += " PASSENGERNO='%s'"%rec[1]

        self.cursor.execute(temp_sqlstring1)
        data1 = self.cursor.fetchall()
        for rec in data1:
            self.lineEdit_19.setText(rec[1])
            self.lineEdit_20.setText(rec[2])
            self.lineEdit_28.setText(rec[3])
            self.lineEdit_29.setText(rec[4])
            self.lineEdit_30.setText(rec[6])
            self.lineEdit_31.setText(rec[7])
            self.lineEdit_32.setText(str(rec[8]))
            self.lineEdit_33.setText(str(rec[9]))
            self.lineEdit_34.setText((rec[10]))
            self.lineEdit_35.setText((rec[11]))
            self.lineEdit_36.setText((rec[12]))
            self.lineEdit_43.setText((rec[13]))

        # self.cursor.execute(temp_sqlstring2)
        # data = self.cursor.fetchall()
        # for rec in data:
        #     self.lineEdit_21.setText(rec[5])
        #     self.lineEdit_22.setText(rec[6])
        #     self.lineEdit_23.setText(rec[7])
        #     self.lineEdit_24.setText(rec[8])
        #     self.lineEdit_25.setText(rec[9])
        #     self.lineEdit_26.setText(rec[11])
        #     self.lineEdit_27.setText(str(rec[17]))
        #     self.lineEdit_42.setText(str(rec[15]))



    def buttonoutfile(self):
        self.cursor.close()
        self.conn.close()
        self.close()


#===============================================ESC退出界面=======================================
    def keyPressEvent(self, e):  # 不懂这个函数用在哪里？
        # 重写控件centralwidget的键盘按下事件
        if e.key() == QtCore.Qt.Key_Escape:
            # 如果按下了ESC键则执行buttonExit函数
            self.buttonExit()


#=================================实时刷新部分====================================
    def buttonstart(self, data):  # 多线程下用每秒发送的data执行的函数
         #==========================断开数据库======================================
        #  self.cur.close()
        #  self.conn.close()
        # # #============================连接数据库======================================
        #  self.conn = MySQLdb.connect(
        #      host='localhost',
        #      user='root',
        #      passwd='123456',
        #      db='wenzhou',
        #      #
        #     charset='utf8',
        #  )
        #  self.cur = self.conn.cursor()

         self.cursor.execute(str(data))
         alldata = self.cursor.fetchall()
         temp_sqlstring1 = self.sqlstring1
         for rec in alldata:
             self.lineEdit.setText(rec[5])
             self.lineEdit_2.setText(rec[6])
             self.lineEdit_3.setText(rec[7])
             self.lineEdit_4.setText(rec[8])
             self.lineEdit_5.setText(rec[9])
             self.lineEdit_6.setText(rec[11])
             self.lineEdit_7.setText(str(rec[17]))
             self.lineEdit_41.setText(str(rec[15]))
             temp_sqlstring1 += " PASSENGERNO='%s'" % rec[1]

         self.cursor.execute(temp_sqlstring1)
         data1 = self.cursor.fetchall()
         for rec in data1:
             self.lineEdit_18.setText(rec[1])
             self.lineEdit_40.setText(rec[2])
             self.lineEdit_17.setText(rec[3])
             self.lineEdit_8.setText(rec[4])
             self.lineEdit_9.setText(rec[6])
             self.lineEdit_10.setText(rec[7])
             self.lineEdit_11.setText(str(rec[8]))
             self.lineEdit_12.setText(str(rec[9]))
             self.lineEdit_13.setText((rec[10]))
             self.lineEdit_14.setText((rec[11]))
             self.lineEdit_15.setText((rec[12]))
             self.lineEdit_16.setText((rec[13]))


class Backend(QThread):
    update_date = pyqtSignal(str)
    def run(self):
        while True:
            # data = "select * from PSG_AJ_OCR"
            data = "select * from（select * from PSG_AJ_OCR order by NO desc）where rownum=1"
            self.update_date.emit(data)
            time.sleep(3)


class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MyWindow, self).__init__()
        self.setupUi(self)

        self.pushButton.clicked.connect(self.buttonsearch)
        self.pushButton_2.clicked.connect(self.buttonclear)
        self.pushButton_3.clicked.connect(self.buttonoutfile)
        self.pushButton_4.clicked.connect(self.buttonExit)

        self.b = Backend()
        self.b.update_date.connect(self.buttonstart)
        self.b.start()


#=========================================登入界面的输入账号和密码窗口定义===============================================
class LoginDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        QtWidgets.QDialog.__init__(self, parent)
        self.setWindowTitle('天津')
        self.user = QtWidgets.QLineEdit(self)
        self.user.move(10, 20)
        self.user.setText('')
        self.pwd = QtWidgets.QLineEdit(self)
        self.pwd.move(10, 60)
        self.pwd.setText('')
        self.pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginBtn = QtWidgets.QPushButton('Login', self)
        self.loginBtn.move(100, 90)
        self.loginBtn.clicked.connect(self.login)  # 绑定方法判断用户名和密码

    def login(self):
        if self.user.text() == 'tianjin' and self.pwd.text() == 'tianjin':
            # 如果用户名和密码正确，关闭对话框，accept()关闭后，如果增加一个取消按钮调用reject()
            self.accept()
        else:
            QtWidgets.QMessageBox.critical(self, 'Error', 'User name or password error')


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)  # 建立一个app，把框架放在这个app中执行
    app.aboutToQuit.connect(app.deleteLater)
    pixmap = QtGui.QPixmap()
    dialog = LoginDialog()
    # if dialog.exec_():
    #     myshow = MyWindow()
    #     myshow.setStyleSheet("#MainWindow{border-image:url(./timg.jpg);}")
    #     myshow.show()
    #     sys.exit(app.exec_())  # 也可以写成app.exec_() sys.exit(0)，前者是循环整个界面，后者是退出app
    myshow = MyWindow()
    myshow.setStyleSheet("#MainWindow{border-image:url(./timg.jpg);}")
    myshow.show()
    sys.exit(app.exec_())

